qcodec2wrapper: fix C++ compatibility issue of std::atomic<std::shared_ptr>
Use std::shared_ptr + std::mutex to mimic C++20 std::atomic<std::shared_ptr>
which is not supported in old GCC11.

Compilation error on GCC11 in yocto kirkstone:
c++/11.3.0/atomic:211:7: error: static_assert failed due to requirement
'__is_trivially_copyable(std::shared_ptr<QTI::EventCallback>)'
"std::atomic requires a trivially copyable type"

Change-Id: I4479148223521a3298c8e6ece578243fe08f4db7
Signed-off-by: Ferry Zhou <tianguiz@qti.qualcomm.com>